<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
  <meta charset="utf-8">
  <meta name="generator" content="quarto-0.3.17">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title>Museum Data Join</title>
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      {   }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ff0000; font-weight: bold; } /* Alert */
    code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
    code span.at { color: #7d9029; } /* Attribute */
    code span.bn { color: #40a070; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #4070a0; } /* Char */
    code span.cn { color: #880000; } /* Constant */
    code span.co { color: #60a0b0; font-style: italic; } /* Comment */
    code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
    code span.do { color: #ba2121; font-style: italic; } /* Documentation */
    code span.dt { color: #902000; } /* DataType */
    code span.dv { color: #40a070; } /* DecVal */
    code span.er { color: #ff0000; font-weight: bold; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #40a070; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
    code span.kw { color: #007020; font-weight: bold; } /* Keyword */
    code span.op { color: #666666; } /* Operator */
    code span.ot { color: #007020; } /* Other */
    code span.pp { color: #bc7a00; } /* Preprocessor */
    code span.sc { color: #4070a0; } /* SpecialChar */
    code span.ss { color: #bb6688; } /* SpecialString */
    code span.st { color: #4070a0; } /* String */
    code span.va { color: #19177c; } /* Variable */
    code span.vs { color: #4070a0; } /* VerbatimString */
    code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
  </style>

  <script src="MuseumDataJoin_files/libs/clipboard/clipboard.min.js"></script>
  <script src="MuseumDataJoin_files/libs/quarto-html/quarto.js"></script>
  <script src="MuseumDataJoin_files/libs/quarto-html/popper.min.js"></script>
  <script src="MuseumDataJoin_files/libs/quarto-html/tippy.umd.min.js"></script>
  <script src="MuseumDataJoin_files/libs/quarto-html/anchor.min.js"></script>
  <link href="MuseumDataJoin_files/libs/quarto-html/tippy.css" rel="stylesheet">
  <link href="MuseumDataJoin_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
  <script src="MuseumDataJoin_files/libs/bootstrap/bootstrap.min.js"></script>
  <link href="MuseumDataJoin_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
  <link href="MuseumDataJoin_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet">
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<div id="quarto-content" class="container-fluid page-layout-article">
<div class="page-columns">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <div id="quarto-toc-target"></div>
</div>
<main class="content">
<header id="title-block-header">
<h1 class="title display-7">Museum Data Join</h1>
<p class="date">02.14.2022</p>
</header>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Warning in system("timedatectl", intern = TRUE): running command 'timedatectl'
had status 1</code></pre>
</div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>gardner <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/gardner.csv"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#loadjanson</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>janson <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/janson.csv"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#loadMoMA</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>moma <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/moma.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Warning: One or more parsing issues, see `problems()` for details</code></pre>
</div>
<div class="sourceCode" id="cb5"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#loadCountMoMAExh</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>countmoma <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/countmoma.csv"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#loadWhitney</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>whitney <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/whitney.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>join gardner and janson with column = book, janson, gardner</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>janson <span class="ot">&lt;-</span> janson <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">ArtistNationalityOther =</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">case_when</span>((ArtistNationality <span class="sc">!=</span> <span class="st">"French"</span>) <span class="sc">&amp;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                       (ArtistNationality <span class="sc">!=</span> <span class="st">"American"</span>) <span class="sc">&amp;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                       (ArtistNationality <span class="sc">!=</span> <span class="st">"German"</span>) <span class="sc">&amp;</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                       (ArtistNationality <span class="sc">!=</span> <span class="st">"Spanish"</span>) <span class="sc">&amp;</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                       (ArtistNationality <span class="sc">!=</span> <span class="st">"British"</span>) </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                                          <span class="sc">~</span> <span class="st">"Other"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>             (ArtistNationality <span class="sc">==</span> <span class="st">"French"</span> <span class="sc">~</span> <span class="st">"French"</span>),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>             (ArtistNationality <span class="sc">==</span> <span class="st">"British"</span> <span class="sc">~</span> <span class="st">"British"</span>),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>             (ArtistNationality <span class="sc">==</span> <span class="st">"American"</span> <span class="sc">~</span> <span class="st">"American"</span>),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>             (ArtistNationality <span class="sc">==</span> <span class="st">"Spanish"</span> <span class="sc">~</span> <span class="st">"Spanish"</span>),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>             (ArtistNationality <span class="sc">==</span> <span class="st">"German"</span> <span class="sc">~</span> <span class="st">"German"</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ArtistName, </span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>        EditionNumber,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>        Year,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>        ArtistNationalityOther,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>        ArtistGender, </span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>        ArtistRace, </span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>        ArtistEthnicity, </span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>        Book)<span class="sc">%&gt;%</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">SpaceRatioPerPage =</span> <span class="fu">sum</span>(SpaceRatioPerPage))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'ArtistName', 'EditionNumber', 'Year', 'ArtistNationalityOther', 'ArtistGender', 'ArtistRace', 'ArtistEthnicity'. You can override using the `.groups` argument.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>gardner <span class="ot">&lt;-</span> gardner <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">ArtistNationalityOther =</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">case_when</span>((ArtistNationality <span class="sc">!=</span> <span class="st">"French"</span>) <span class="sc">&amp;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                       (ArtistNationality <span class="sc">!=</span> <span class="st">"American"</span>) <span class="sc">&amp;</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                       (ArtistNationality <span class="sc">!=</span> <span class="st">"German"</span>) <span class="sc">&amp;</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                       (ArtistNationality <span class="sc">!=</span> <span class="st">"Spanish"</span>) <span class="sc">&amp;</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                       (ArtistNationality <span class="sc">!=</span> <span class="st">"British"</span>) </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                                          <span class="sc">~</span> <span class="st">"Other"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>             (ArtistNationality <span class="sc">==</span> <span class="st">"French"</span> <span class="sc">~</span> <span class="st">"French"</span>),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>             (ArtistNationality <span class="sc">==</span> <span class="st">"British"</span> <span class="sc">~</span> <span class="st">"British"</span>),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>             (ArtistNationality <span class="sc">==</span> <span class="st">"American"</span> <span class="sc">~</span> <span class="st">"American"</span>),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>             (ArtistNationality <span class="sc">==</span> <span class="st">"Spanish"</span> <span class="sc">~</span> <span class="st">"Spanish"</span>),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>             (ArtistNationality <span class="sc">==</span> <span class="st">"German"</span> <span class="sc">~</span> <span class="st">"German"</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ArtistName, </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>        EditionNumber,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>        Year,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>        ArtistNationalityOther,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>        ArtistGender, </span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>        ArtistRace, </span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>        ArtistEthnicity, </span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>        Book)<span class="sc">%&gt;%</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">SpaceRatioPerPage =</span> <span class="fu">sum</span>(SpaceRatioPerPage))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'ArtistName', 'EditionNumber', 'Year', 'ArtistNationalityOther', 'ArtistGender', 'ArtistRace', 'ArtistEthnicity'. You can override using the `.groups` argument.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>gardnerjanson <span class="ot">&lt;-</span> gardner <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(janson, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"ArtistName"</span>, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"EditionNumber"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Year"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"ArtistNationalityOther"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"ArtistGender"</span>, </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"ArtistRace"</span>, </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"ArtistEthnicity"</span>, </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Book"</span>, </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"SpaceRatioPerPage"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>countmomacleanNA</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>countmoma <span class="ot">&lt;-</span> countmoma <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">TotalAreaText(cm^2)</span><span class="st">`</span><span class="sc">!=</span> <span class="st">"NA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>join gardnerjanson with MoMA through antijoin - showing gardnerjanson that is NOT in MoMA - compare directly with moma?</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>antimomagardnerjanson <span class="ot">&lt;-</span> gardnerjanson <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(moma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Joining, by = c("ArtistName", "Year")</code></pre>
</div>
</div>
<p>clean artist name manually using gardnerjanson name</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>antiwhitneygardnerjanson <span class="ot">&lt;-</span> gardnerjanson <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(whitney)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Joining, by = c("ArtistName", "Year")</code></pre>
</div>
</div>
<p>join gardnerjansonMoMa with Whitney through antijoin</p>
<p>arrange(ArtistName, EndYear)%&gt;%</p>
<p>group_by(ArtistName)%&gt;%</p>
<p>mutate(count_to_date = cumsum(count))%&gt;%</p>
<p>select(ArtistName, count_to_date)</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>moma <span class="ot">&lt;-</span> moma <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">count =</span> <span class="dv">1</span>)<span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(ArtistName, Year)<span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ArtistName)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>momagardnerjanson <span class="ot">&lt;-</span> gardnerjanson <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(moma, <span class="at">by =</span> <span class="st">"ArtistName"</span>, <span class="st">"Year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>whitney <span class="ot">&lt;-</span> whitney <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">count =</span> <span class="dv">1</span>)<span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(ArtistName, Year)<span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ArtistName)<span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">count_to_date =</span> <span class="fu">cumsum</span>(count))<span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ArtistName, count_to_date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>whitneygardnerjanson <span class="ot">&lt;-</span> gardnerjanson <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(whitney)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Joining, by = "ArtistName"</code></pre>
</div>
</div>
<p>EDA: Bivariate Plots and MLR with SpaceRatio</p>
<p>Janson:</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(janson, <span class="fu">aes</span>(<span class="at">x =</span> SpaceRatioPerPage, <span class="at">fill =</span> EditionNumber))<span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()<span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Ratio of Space </span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="st">       per Artist per Edition per Page in Janson"</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Ratio of Space per Page"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="MuseumDataJoin_files/figure-html/countjanson-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb23"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(janson<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0946  0.2635  0.3768  0.5317  0.6516  3.7967 </code></pre>
</div>
<div class="sourceCode" id="cb25"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(janson<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.3768331</code></pre>
</div>
<div class="sourceCode" id="cb27"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(janson<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.3880623</code></pre>
</div>
<div class="sourceCode" id="cb29"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>janson<span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(SpaceRatioPerPage))<span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ArtistName, EditionNumber, Year, SpaceRatioPerPage)<span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SpaceRatioPerPage <span class="sc">&gt;=</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Adding missing grouping variables: `ArtistNationalityOther`, `ArtistGender`, `ArtistRace`, `ArtistEthnicity`</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 15 × 8
# Groups:   ArtistName, EditionNumber, Year, ArtistNationalityOther,
#   ArtistGender, ArtistRace, ArtistEthnicity [15]
   ArtistNationalityOther ArtistGender ArtistRace ArtistEthnicity   ArtistName  
   &lt;chr&gt;                  &lt;chr&gt;        &lt;chr&gt;      &lt;chr&gt;             &lt;chr&gt;       
 1 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
 2 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
 3 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
 4 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
 5 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
 6 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
 7 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
 8 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
 9 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
10 French                 Male         White      Not Hispanic or … Claude Monet
11 French                 Male         White      Not Hispanic or … Eugène Dela…
12 French                 Male         White      Not Hispanic or … Eugène Dela…
13 Other                  Male         White      Not Hispanic or … Vincent van…
14 French                 Male         White      Not Hispanic or … Jean August…
15 French                 Male         White      Not Hispanic or … Paul Cézanne
# … with 3 more variables: EditionNumber &lt;dbl&gt;, Year &lt;dbl&gt;,
#   SpaceRatioPerPage &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The visualization above is right skewed, unimodal and assymetrical. Therefore, we would want to look at the median to understand its center and IQR to understand its spread. The median of <code>SpaceRatioPerPage</code> in Janson is 0.377 and the IQR is 0.388. There are potential outliers that are over 2.0, meaning the amount of space, area of text and area of figure in text combined is more than just the area of a single page within the respective book of <em>Janson’s History of Art.</em> It is obvious to observe that Spanish painter, Pablo Picasso dominates space through all editions of Janson.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(janson, <span class="fu">aes</span>(<span class="at">x=</span>ArtistGender, <span class="at">y=</span> SpaceRatioPerPage))<span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ratio of Space per Page per Artist per Edition in </span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="st">       Janson by Gender"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Gender"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ratio of Space per Page"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MuseumDataJoin_files/figure-html/genderjanson-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb33"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>janson_female <span class="ot">&lt;-</span> janson <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ArtistGender <span class="sc">==</span> <span class="st">"Female"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>janson_female <span class="sc">%&gt;%</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SpaceRatioPerPage <span class="sc">&gt;</span> .<span class="dv">63</span>)<span class="sc">%&gt;%</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ArtistName, ArtistGender, EditionNumber, Year, SpaceRatioPerPage)<span class="sc">%&gt;%</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(SpaceRatioPerPage))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Adding missing grouping variables: `ArtistNationalityOther`, `ArtistRace`, `ArtistEthnicity`</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 10 × 8
# Groups:   ArtistName, EditionNumber, Year, ArtistNationalityOther,
#   ArtistGender, ArtistRace, ArtistEthnicity [10]
   ArtistNationalityOther ArtistRace ArtistEthnicity   ArtistName   ArtistGender
   &lt;chr&gt;                  &lt;chr&gt;      &lt;chr&gt;             &lt;chr&gt;        &lt;chr&gt;       
 1 German                 White      Not Hispanic or … Hannah Höch  Female      
 2 German                 White      Not Hispanic or … Hannah Höch  Female      
 3 Other                  White      Not Hispanic or … Angelica Ka… Female      
 4 Other                  White      Not Hispanic or … Liubov Popo… Female      
 5 Other                  White      Not Hispanic or … Angelica Ka… Female      
 6 American               White      Not Hispanic or … Mary Cassatt Female      
 7 American               White      Not Hispanic or … Susan Rothe… Female      
 8 American               White      Not Hispanic or … Elizabeth M… Female      
 9 American               White      Not Hispanic or … Mary Cassatt Female      
10 French                 White      Not Hispanic or … Rosa Bonheur Female      
# … with 3 more variables: EditionNumber &lt;dbl&gt;, Year &lt;dbl&gt;,
#   SpaceRatioPerPage &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode" id="cb36"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(janson_female<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.3093875</code></pre>
</div>
<div class="sourceCode" id="cb38"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>janson_male <span class="ot">&lt;-</span> janson <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ArtistGender <span class="sc">==</span> <span class="st">"Male"</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(janson_male<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.3921904</code></pre>
</div>
</div>
<p>Interestingly enough, the median <code>SpaceRatioPerPage</code> for female artists is 0.309, not far below the median <code>SpaceRatioPerPage</code> for male artists, 0.392 in <em>Janson’s History of Art.</em> This indicates that even though the number of female artists per edition included is far fewer, 122, the median amount of space given to women is similar to that as the median amount of space given to male artists per edition, 1097. The only female artist that comes close to being larger than 1 for SpaceRatioPerPage is Hannah Hoch, as seen by the table above.</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(janson, <span class="fu">aes</span>(<span class="at">x=</span>ArtistRace, <span class="at">y=</span> SpaceRatioPerPage))<span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ratio of Space per Page per Artist per Edition in </span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="st">       Janson by Race"</span>,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Race"</span>,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ratio of Space per Page"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MuseumDataJoin_files/figure-html/racejanson-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb41"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>janson <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ArtistRace <span class="sc">==</span> <span class="st">"American Indian or Alaska Native"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ArtistName, </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>         ArtistGender, </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>         ArtistRace, </span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>         EditionNumber, </span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>         Year, </span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>         SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Adding missing grouping variables: `ArtistNationalityOther`, `ArtistEthnicity`</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 2 × 8
# Groups:   ArtistName, EditionNumber, Year, ArtistNationalityOther,
#   ArtistGender, ArtistRace, ArtistEthnicity [2]
  ArtistNationalityOther ArtistEthnicity  ArtistName  ArtistGender ArtistRace   
  &lt;chr&gt;                  &lt;chr&gt;            &lt;chr&gt;       &lt;chr&gt;        &lt;chr&gt;        
1 American               Not Hispanic or… Kay Walkin… Female       American Ind…
2 American               Not Hispanic or… Kay Walkin… Female       American Ind…
# … with 3 more variables: EditionNumber &lt;dbl&gt;, Year &lt;dbl&gt;,
#   SpaceRatioPerPage &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode" id="cb44"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>janson <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ArtistRace <span class="sc">==</span> <span class="st">"Asian"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ArtistName, </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>         ArtistGender, </span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>         ArtistRace, </span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>         EditionNumber, </span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>         Year, </span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>         SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Adding missing grouping variables: `ArtistNationalityOther`, `ArtistEthnicity`</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 2 × 8
# Groups:   ArtistName, EditionNumber, Year, ArtistNationalityOther,
#   ArtistGender, ArtistRace, ArtistEthnicity [2]
  ArtistNationalityOther ArtistEthnicity     ArtistName  ArtistGender ArtistRace
  &lt;chr&gt;                  &lt;chr&gt;               &lt;chr&gt;       &lt;chr&gt;        &lt;chr&gt;     
1 Other                  Not Hispanic or La… Ando Hiros… Male         Asian     
2 Other                  Not Hispanic or La… Ando Hiros… Male         Asian     
# … with 3 more variables: EditionNumber &lt;dbl&gt;, Year &lt;dbl&gt;,
#   SpaceRatioPerPage &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode" id="cb47"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>janson <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ArtistRace <span class="sc">==</span> <span class="st">"Black or African American"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ArtistName, </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>         ArtistGender, </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>         ArtistRace, </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>         EditionNumber, </span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>         Year, </span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>         SpaceRatioPerPage)<span class="sc">%&gt;%</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SpaceRatioPerPage <span class="sc">&gt;</span> .<span class="dv">75</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Adding missing grouping variables: `ArtistNationalityOther`, `ArtistEthnicity`</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 1 × 8
# Groups:   ArtistName, EditionNumber, Year, ArtistNationalityOther,
#   ArtistGender, ArtistRace, ArtistEthnicity [1]
  ArtistNationalityOther ArtistEthnicity   ArtistName  ArtistGender ArtistRace  
  &lt;chr&gt;                  &lt;chr&gt;             &lt;chr&gt;       &lt;chr&gt;        &lt;chr&gt;       
1 American               Not Hispanic or … William T.… Male         Black or Af…
# … with 3 more variables: EditionNumber &lt;dbl&gt;, Year &lt;dbl&gt;,
#   SpaceRatioPerPage &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode" id="cb50"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>janson_white <span class="ot">&lt;-</span> janson<span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ArtistRace <span class="sc">==</span> <span class="st">"White"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(SpaceRatioPerPage))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Regarding race, there is only artist for American Indian or Alaska Native, which is Kay Walkingstick in the 5th and 6th Editions and one artist for Asian, Ando Hiroshige in the 7th and 8th Editions. Additionally, there is only one Black or African American artist who has a <code>SpaceRatioPerPage</code> that is over .75, William T. Williams in the 3rd Edition. There are myriad white artists per work per edition, 1187, and their space trumps that of the space allotted to nonwhite artists.</p>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(janson, <span class="fu">aes</span>(<span class="at">x=</span>ArtistEthnicity, <span class="at">y=</span> SpaceRatioPerPage))<span class="sc">+</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ratio of Space per Page per Artist per Edition in</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="st">       Janson by Ethnicity"</span>,</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Ethnicity"</span>,</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ratio of Space per Page"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MuseumDataJoin_files/figure-html/jansonethnicity-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb52"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>janson_HL <span class="ot">&lt;-</span> janson <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ArtistEthnicity <span class="sc">==</span> <span class="st">"Hispanic or Latinx"</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(janson_HL<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.488591</code></pre>
</div>
<div class="sourceCode" id="cb54"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>janson_NHL <span class="ot">&lt;-</span> janson <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ArtistEthnicity <span class="sc">==</span> <span class="st">"Not Hispanic or Latinx"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(janson_NHL<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.374853</code></pre>
</div>
</div>
<p>Interestingly, the median <code>SpaceRatioPerPage</code> for artists who are Hispanic or Latinx, 0.489 is higher than those who are Not Hispanic or Latinx, 0.375. There are 51 observations of artists per edition who are Hispanic and Latinx and there are 1168 observations of artists per edition who are not Hispanic or Latinx. Picasso plays a large role in such, as he is Hispanic or Latinx and is accounting for the outlyingly larger observations for <code>SpaceRatioPerPage</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb56"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(janson, <span class="fu">aes</span>(<span class="at">x=</span>ArtistNationalityOther, <span class="at">y=</span> SpaceRatioPerPage))<span class="sc">+</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ratio of Space per Page per Artist per Edition in </span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="st">       Janson by Nationality"</span>,</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Nationality"</span>,</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ratio of Space per Page"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MuseumDataJoin_files/figure-html/jansonnationality-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>MLR of Janson with Gender +Race + Nationality + Ethnicity ~ SpaceRatioPerPage</p>
<p>STILL NEED TO ACCOUNT OF RANDOM EFFECT OF ARTIST</p>
<div class="cell">
<div class="sourceCode" id="cb57"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>jansonMLR <span class="ot">=</span> <span class="fu">lm</span>(SpaceRatioPerPage <span class="sc">~</span> ArtistRace <span class="sc">+</span> </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>                         ArtistEthnicity <span class="sc">+</span> </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>                         ArtistGender <span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>                         ArtistNationalityOther, </span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> janson)</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(jansonMLR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>
Call:
lm(formula = SpaceRatioPerPage ~ ArtistRace + ArtistEthnicity + 
    ArtistGender + ArtistNationalityOther, data = janson)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.24357 -0.21611 -0.07987  0.13581  2.44164 

Coefficients:
                                        Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                            0.3268360  0.2996234   1.091  0.27557
ArtistRaceAsian                       -0.2136831  0.3992200  -0.535  0.59257
ArtistRaceBlack or African American   -0.1501952  0.2928581  -0.513  0.60814
ArtistRaceWhite                       -0.0681345  0.2828742  -0.241  0.80970
ArtistEthnicityNot Hispanic or Latinx  0.0634828  0.1057870   0.600  0.54855
ArtistGenderMale                       0.1131006  0.0396161   2.855  0.00438
ArtistNationalityOtherBritish          0.0068556  0.0414248   0.165  0.86858
ArtistNationalityOtherFrench           0.2887981  0.0319720   9.033  &lt; 2e-16
ArtistNationalityOtherGerman          -0.0007151  0.0439768  -0.016  0.98703
ArtistNationalityOtherOther            0.0275986  0.0342270   0.806  0.42021
ArtistNationalityOtherSpanish          0.9832489  0.1275469   7.709 2.64e-14
                                         
(Intercept)                              
ArtistRaceAsian                          
ArtistRaceBlack or African American      
ArtistRaceWhite                          
ArtistEthnicityNot Hispanic or Latinx    
ArtistGenderMale                      ** 
ArtistNationalityOtherBritish            
ArtistNationalityOtherFrench          ***
ArtistNationalityOtherGerman             
ArtistNationalityOtherOther              
ArtistNationalityOtherSpanish         ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3964 on 1208 degrees of freedom
Multiple R-squared:  0.1991,    Adjusted R-squared:  0.1925 
F-statistic: 30.04 on 10 and 1208 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb59"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(jansonMLR)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.1991285</code></pre>
</div>
</div>
<p>Gardner:</p>
<div class="cell">
<div class="sourceCode" id="cb61"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gardner, <span class="fu">aes</span>(<span class="at">x =</span> SpaceRatioPerPage))<span class="sc">+</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()<span class="sc">+</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Ratio of Space </span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="st">       per Artist per Edition per Page in Gardner"</span>,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Ratio of Space per Page"</span>,</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="MuseumDataJoin_files/figure-html/countgardner-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb63"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gardner<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1423  0.3371  0.4204  0.5292  0.5760  3.4220 </code></pre>
</div>
<div class="sourceCode" id="cb65"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(gardner<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.4204154</code></pre>
</div>
<div class="sourceCode" id="cb67"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(gardner<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.2388467</code></pre>
</div>
<div class="sourceCode" id="cb69"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>gardner<span class="sc">%&gt;%</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(SpaceRatioPerPage))<span class="sc">%&gt;%</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ArtistName, EditionNumber, Year, SpaceRatioPerPage)<span class="sc">%&gt;%</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SpaceRatioPerPage <span class="sc">&gt;=</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Adding missing grouping variables: `ArtistNationalityOther`, `ArtistGender`, `ArtistRace`, `ArtistEthnicity`</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 24 × 8
# Groups:   ArtistName, EditionNumber, Year, ArtistNationalityOther,
#   ArtistGender, ArtistRace, ArtistEthnicity [24]
   ArtistNationalityOther ArtistGender ArtistRace ArtistEthnicity   ArtistName  
   &lt;chr&gt;                  &lt;chr&gt;        &lt;chr&gt;      &lt;chr&gt;             &lt;chr&gt;       
 1 French                 Male         White      Not Hispanic or … Eugène Dela…
 2 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
 3 French                 Male         White      Not Hispanic or … Eugène Dela…
 4 French                 Male         White      Not Hispanic or … Jacques-Lou…
 5 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
 6 French                 Male         White      Not Hispanic or … Eugène Dela…
 7 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
 8 French                 Male         White      Not Hispanic or … Eugène Dela…
 9 Spanish                Male         White      Hispanic or Lati… Francisco G…
10 Spanish                Male         White      Hispanic or Lati… Pablo Picas…
# … with 14 more rows, and 3 more variables: EditionNumber &lt;dbl&gt;, Year &lt;dbl&gt;,
#   SpaceRatioPerPage &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The visualization above is right skewed, unimodal and assymetrical. Therefore, we would want to look at the median to understand its center and IQR to understand its spread. The median of <code>SpaceRatioPerPage</code> in Gardner is 0.42 and the IQR is 0.239. There are potential outliers that are over 2.0, meaning the amount of space, area of text and area of figure in text combined is more than just the area of a single page within the respective book of <em>Gardner’s Art Through the Ages.</em> It is obvious to observe that Spanish painter, Pablo Picasso dominates space through Gardner’s, similarly as he did in <em>Janson’s History of Art,</em> but he has more company this time around. French painters such as Delacroix and Jacques-Louis David also occupy substantial space, particularly in the 10th edition.</p>
<div class="cell">
<div class="sourceCode" id="cb72"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gardner, <span class="fu">aes</span>(<span class="at">x=</span>ArtistGender, <span class="at">y=</span> SpaceRatioPerPage))<span class="sc">+</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ratio of Space per Page per Artist per Edition in </span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="st">       Gardner by Gender"</span>,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Gender"</span>,</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ratio of Space per Page"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MuseumDataJoin_files/figure-html/gardnergender-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb73"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>gardner_female <span class="ot">&lt;-</span> gardner <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ArtistGender <span class="sc">==</span> <span class="st">"Female"</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>gardner_female <span class="sc">%&gt;%</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SpaceRatioPerPage <span class="sc">&gt;</span> .<span class="dv">6</span>)<span class="sc">%&gt;%</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ArtistName, ArtistGender, EditionNumber, Year, SpaceRatioPerPage)<span class="sc">%&gt;%</span></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(SpaceRatioPerPage))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Adding missing grouping variables: `ArtistNationalityOther`, `ArtistRace`, `ArtistEthnicity`</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 9 × 8
# Groups:   ArtistName, EditionNumber, Year, ArtistNationalityOther,
#   ArtistGender, ArtistRace, ArtistEthnicity [9]
  ArtistNationalityOther ArtistRace ArtistEthnicity   ArtistName    ArtistGender
  &lt;chr&gt;                  &lt;chr&gt;      &lt;chr&gt;             &lt;chr&gt;         &lt;chr&gt;       
1 German                 White      Not Hispanic or … Hannah Höch   Female      
2 French                 White      Not Hispanic or … Élisabeth Lo… Female      
3 American               White      Not Hispanic or … Cindy Sherman Female      
4 Other                  White      Not Hispanic or … Angelica Kau… Female      
5 Other                  White      Not Hispanic or … Dorothea Roc… Female      
6 German                 White      Not Hispanic or … Gunta Stölzl  Female      
7 Other                  White      Hispanic or Lati… Frida Kahlo   Female      
8 American               White      Not Hispanic or … Georgia O'Ke… Female      
9 German                 White      Not Hispanic or … Hannah Höch   Female      
# … with 3 more variables: EditionNumber &lt;dbl&gt;, Year &lt;dbl&gt;,
#   SpaceRatioPerPage &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode" id="cb76"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(gardner_female<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.368567</code></pre>
</div>
<div class="sourceCode" id="cb78"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>gardner_male <span class="ot">&lt;-</span> gardner <span class="sc">%&gt;%</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ArtistGender <span class="sc">==</span> <span class="st">"Male"</span>)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(gardner_male<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.4355323</code></pre>
</div>
<div class="sourceCode" id="cb80"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>gardner_male1 <span class="ot">&lt;-</span> gardner_male <span class="sc">%&gt;%</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SpaceRatioPerPage <span class="sc">&gt;</span> <span class="dv">1</span>)<span class="sc">%&gt;%</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ArtistName, </span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>         ArtistGender, </span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>         EditionNumber, </span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>         Year, </span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>         SpaceRatioPerPage)<span class="sc">%&gt;%</span></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(SpaceRatioPerPage))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Adding missing grouping variables: `ArtistNationalityOther`, `ArtistRace`, `ArtistEthnicity`</code></pre>
</div>
<div class="sourceCode" id="cb82"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>gardner_NAgender <span class="ot">&lt;-</span> gardner <span class="sc">%&gt;%</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ArtistGender <span class="sc">==</span> <span class="st">"N/A"</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(gardner_NAgender<span class="sc">$</span>SpaceRatioPerPage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.4116867</code></pre>
</div>
</div>
<p>The median <code>SpaceRatioPerPage</code> for female artists is 0.309 is below the median for artists whose gender is unknown, 0.4116867, as well as the median for male artists 0.436 in <em>Gardner’s Art Through the Ages.</em> The number of artists whose gender is unknown has the fewest observations, 64, the number of female artists is slightly greater, 214, and the amount of male artists through editions is, 1665. The only female artist that comes close to being larger than 1 for <code>SpaceRatioPerPage</code> is again Hannah Hoch, as seen by the table above. Male artists have a dramatic amount of outlying artists through editions over a <code>SpaceRatioPerPage</code> of 1, 154.</p>
<div class="cell">
<div class="sourceCode" id="cb84"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gardner, <span class="fu">aes</span>(<span class="at">x=</span>ArtistRace, <span class="at">y=</span> SpaceRatioPerPage))<span class="sc">+</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ratio of Space per Page per Artist per Edition in </span></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="st">       Gardner by Race"</span>,</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Race"</span>,</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ratio of Space per Page"</span>)<span class="sc">+</span></span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>   <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">size =</span> <span class="dv">5</span>))<span class="sc">+</span></span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fl">2.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Warning: Removed 24 rows containing non-finite values (stat_boxplot).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="MuseumDataJoin_files/figure-html/gardnerrace-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What sticks out like a sore thumb in the visualization above is the significant number of outlying white artists. The only artists that have a <code>SpaceRatioPerPage</code> of 1 or more are white. Though all the medians of race range between .25 and .6,</p>
<div class="cell">
<div class="sourceCode" id="cb86"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gardner, <span class="fu">aes</span>(<span class="at">x=</span>ArtistEthnicity, <span class="at">y=</span> SpaceRatioPerPage))<span class="sc">+</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ratio of Space per Page per Artist per Edition in </span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="st">       Gardner by Ethnicity"</span>,</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Ethnicity"</span>,</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ratio of Space per Page"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MuseumDataJoin_files/figure-html/gardnerethnicity-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Across all three categories, Hispanic or Latinx, Not Hispanic or Latinx and N/A, the medians remain relatively similar. The tail for Hispanic or Latinx are comparable to the tail for Not Hispanic or Latinx, just simply the number of observations are far fewer.</p>
<div class="cell">
<div class="sourceCode" id="cb87"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gardner, <span class="fu">aes</span>(<span class="at">x=</span>ArtistNationalityOther, <span class="at">y=</span> SpaceRatioPerPage))<span class="sc">+</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ratio of Space per Page per Artist per Edition in </span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="st">       Gardner by Nationality"</span>,</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Nationality"</span>,</span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ratio of Space per Page"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MuseumDataJoin_files/figure-html/gardnernationality-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>GardnerMLR Demographic</p>
<div class="cell">
<div class="sourceCode" id="cb88"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>gardnerMLR <span class="ot">=</span> <span class="fu">lm</span>(SpaceRatioPerPage <span class="sc">~</span> ArtistRace <span class="sc">+</span> </span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>                         ArtistEthnicity <span class="sc">+</span> </span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>                         ArtistGender <span class="sc">+</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>                         ArtistNationalityOther, </span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> gardner)</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gardnerMLR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>
Call:
lm(formula = SpaceRatioPerPage ~ ArtistRace + ArtistEthnicity + 
    ArtistGender + ArtistNationalityOther, data = gardner)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.88208 -0.15552 -0.04639  0.08305  2.71322 

Coefficients:
                                                      Estimate Std. Error
(Intercept)                                          0.3706069  0.1346464
ArtistRaceAsian                                     -0.0985929  0.1277068
ArtistRaceBlack or African American                 -0.0223035  0.1319777
ArtistRaceN/A                                       -0.1851459  0.1295896
ArtistRaceNative American                            0.0291433  0.2541767
ArtistRaceNative Hawaiian or Other Pacific Islander -0.0920900  0.1381601
ArtistRaceWhite                                     -0.0256360  0.1255178
ArtistEthnicityN/A                                  -0.1161134  0.1621978
ArtistEthnicityNot Hispanic or Latinx               -0.0103408  0.0495540
ArtistGenderMale                                     0.0941771  0.0237638
ArtistGenderN/A                                      0.2533941  0.1597795
ArtistNationalityOtherBritish                        0.0395316  0.0274741
ArtistNationalityOtherFrench                         0.2799373  0.0199520
ArtistNationalityOtherGerman                        -0.0007043  0.0300185
ArtistNationalityOtherOther                          0.0391254  0.0232386
ArtistNationalityOtherSpanish                        0.7480272  0.0669148
                                                    t value Pr(&gt;|t|)    
(Intercept)                                           2.752  0.00597 ** 
ArtistRaceAsian                                      -0.772  0.44019    
ArtistRaceBlack or African American                  -0.169  0.86582    
ArtistRaceN/A                                        -1.429  0.15325    
ArtistRaceNative American                             0.115  0.90873    
ArtistRaceNative Hawaiian or Other Pacific Islander  -0.667  0.50514    
ArtistRaceWhite                                      -0.204  0.83819    
ArtistEthnicityN/A                                   -0.716  0.47415    
ArtistEthnicityNot Hispanic or Latinx                -0.209  0.83472    
ArtistGenderMale                                      3.963 7.67e-05 ***
ArtistGenderN/A                                       1.586  0.11293    
ArtistNationalityOtherBritish                         1.439  0.15035    
ArtistNationalityOtherFrench                         14.031  &lt; 2e-16 ***
ArtistNationalityOtherGerman                         -0.023  0.98128    
ArtistNationalityOtherOther                           1.684  0.09241 .  
ArtistNationalityOtherSpanish                        11.179  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3194 on 1927 degrees of freedom
Multiple R-squared:  0.2277,    Adjusted R-squared:  0.2216 
F-statistic: 37.87 on 15 and 1927 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb90"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(gardnerMLR)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.2276613</code></pre>
</div>
</div>
<p>MLR demograpic with jansongardner</p>
<div class="cell">
<div class="sourceCode" id="cb92"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>gardnerjansonMLR <span class="ot">=</span> <span class="fu">lm</span>(SpaceRatioPerPage <span class="sc">~</span> ArtistRace <span class="sc">+</span> </span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>                         ArtistEthnicity <span class="sc">+</span> </span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>                         ArtistGender <span class="sc">+</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>                         ArtistNationalityOther, </span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> gardnerjanson)</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gardnerjansonMLR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>
Call:
lm(formula = SpaceRatioPerPage ~ ArtistRace + ArtistEthnicity + 
    ArtistGender + ArtistNationalityOther, data = gardnerjanson)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.13999 -0.17850 -0.05639  0.09960  2.70755 

Coefficients:
                                                     Estimate Std. Error
(Intercept)                                          0.358294   0.128735
ArtistRaceAsian                                     -0.104493   0.123862
ArtistRaceBlack or African American                 -0.054966   0.126027
ArtistRaceN/A                                       -0.187826   0.131320
ArtistRaceNative American                            0.026362   0.274142
ArtistRaceNative Hawaiian or Other Pacific Islander -0.096192   0.140555
ArtistRaceWhite                                     -0.032176   0.120576
ArtistEthnicityN/A                                  -0.102174   0.175547
ArtistEthnicityNot Hispanic or Latinx                0.004919   0.046627
ArtistGenderMale                                     0.099188   0.020848
ArtistGenderN/A                                      0.258150   0.174600
ArtistNationalityOtherBritish                        0.027457   0.023249
ArtistNationalityOtherFrench                         0.284196   0.017305
ArtistNationalityOtherGerman                         0.000415   0.025125
ArtistNationalityOtherOther                          0.035524   0.019437
ArtistNationalityOtherSpanish                        0.826162   0.060736
                                                    t value Pr(&gt;|t|)    
(Intercept)                                           2.783  0.00541 ** 
ArtistRaceAsian                                      -0.844  0.39894    
ArtistRaceBlack or African American                  -0.436  0.66276    
ArtistRaceN/A                                        -1.430  0.15273    
ArtistRaceNative American                             0.096  0.92340    
ArtistRaceNative Hawaiian or Other Pacific Islander  -0.684  0.49379    
ArtistRaceWhite                                      -0.267  0.78960    
ArtistEthnicityN/A                                   -0.582  0.56059    
ArtistEthnicityNot Hispanic or Latinx                 0.105  0.91599    
ArtistGenderMale                                      4.758 2.05e-06 ***
ArtistGenderN/A                                       1.479  0.13937    
ArtistNationalityOtherBritish                         1.181  0.23770    
ArtistNationalityOtherFrench                         16.423  &lt; 2e-16 ***
ArtistNationalityOtherGerman                          0.017  0.98682    
ArtistNationalityOtherOther                           1.828  0.06769 .  
ArtistNationalityOtherSpanish                        13.603  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3509 on 3146 degrees of freedom
Multiple R-squared:  0.2119,    Adjusted R-squared:  0.2082 
F-statistic:  56.4 on 15 and 3146 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb94"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(gardnerjansonMLR)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 0.2119241</code></pre>
</div>
</div>
<p>whitney eda</p>
<p>{r whitneycounttodate} ggplot(whitneygardnerjanson, aes(x = count_to_date))+ geom_histogram()+ labs(title = “Distribution of Whitney Exhibitions per Artist per Edition”, x = “Count to Date”, y = “Count”)</p>
<p>{r whitneyvisual} ggplot(whitneygardnerjanson, aes(x = count_to_date, y = SpaceRatioPerPage))+ geom_point()+ labs(title = “Ratio of Space Per Artist Per Edition by Number of Exhibitions per Artist per Editions in the Whitney”, x = “Count to Date”, y = “Ratio of Space Per Artist Per Edition”)</p>
<p>moma eda</p>
<p>{r momacounttodate} ggplot(momagardnerjanson, aes(x = count_to_date))+ geom_histogram()+ labs(title = “Distribution of MoMA Exhibitions per Artist per Edition”, x = “Count to Date”, y = “Count”)</p>
<p>{r momavisual} ggplot(momagardnerjanson, aes(x = count_to_date, y = SpaceRatioPerPage))+ geom_point()+ labs(title = “Ratio of Space Per Artist Per Edition by Number of Exhibitions per Artist per Editions in the MoMA”, x = “Count to Date”, y = “Ratio of Space Per Artist Per Edition”)</p>
</main>
<!-- /main column -->
<script type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    setTimeout(function() {
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /grid -->
</div> <!-- /content -->


</body></html>